### ISSUE TITLE
Instructions for Swift need an additional step

### ISSUE THREAD

**Issue by Tybion** [ngageoint/simple-features-wkb-ios#11]
The documentation for using in Swift 4 did not work for me.

I needed to specify the full path of the bridging header ..

#import "../Pods/wkb-ios/wkb-ios/wkb-ios-Bridging-Header.h"

.. and then copy all the .h files to the same folder.

Presumably, this would be better solved by changing the header search path in Xcode, but I am very new to Xcode, so wasn't sure of the correct way to do this.

Can you please add the best solution for this problem to the docs, because it will be a problem for any other developers that are new to Xcode?

#### Version Information:

  * WKB iOS Version: 9.3
  * WKB iOS Source: CocoaPods
  * CocoaPods Version: 1.3.1
  * Xcode Version: 9.2
  * Device or Emulator: NA
  * iOS Version: NA

**Comment by bosborn** [comment]
I created a new Swift 4 project and did not find any issues.  Did you you create & configure a bridging header for your Swift project?

Under Build Settings for Objective-C Bridging Header you should have the relative path (similar to the Info.plist setting path) to the project's bridging header (`<folder>/<name>-Bridging-Header.h`).  The `<folder>/<name>-Bridging-Header.h` file should specify:
`#import "wkb-ios-Bridging-Header.h"`

I was able to use the library without any additional imports.

[Here is a link from Apple](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) on mixing between Objective-C and Swift.

**Comment by Tybion** [comment]
Thanks, Brian for re-testing.

I created a bridging header in Xcode 'automatically' and Xcode created it in the following general project folder, and this is what Xcode wrote in **Build Settings** ..
`ausgeologymaps/ausgeologymaps-Bridging-Header.h`

The line within my **ausgeologymaps-Bridging-Header.h** is ..
`#import "../Pods/wkb-ios/wkb-ios/wkb-ios-Bridging-Header.h"`

Looking for the differences between you and me - you created a **new** Swift project.  Did you put the **project** bridging header in the same folder as the **wkb-ios** bridging header?

**Comment by bosborn** [comment]
Your bridging header file location seems good.  You should be able to remove the relative location path from the import line.
#import "~~../Pods/wkb-ios/wkb-ios/~~ wkb-ios-Bridging-Header.h" 
resulting in an `ausgeologymaps/ausgeologymaps-Bridging-Header.h` file something like:
```
#ifndef ausgeologymaps_Bridging_Header_h
#define ausgeologymaps_Bridging_Header_h

#import "wkb-ios-Bridging-Header.h"

#endif /* ausgeologymaps_Bridging_Header_h */
```
The Objective-C Bridging Header setting under the project Build Settings should be:
`ausgeologymaps/ausgeologymaps-Bridging-Header.h`
For verification purposes, you should probably see a Info.plist file in the same directory as your bridging header.  Under the building settings, confirm the relative path is similar as your specified bridging header.
Something like... `Info.plist File: ausgeologymaps/Info.plist`

I assume in your `Podfile` you have the dependency listed as:
`pod 'wkb-ios', '~> 1.0.9'`

After running `pod install`, make sure you are opening & using the `ausgeologymaps.xcworkspace` project and not `ausgeologymaps.xcodeproj`.

Here is a screen shot of the example project layout and build settings that I created.

![screen shot 2018-03-13 at 6 23 55 am](https://user-images.githubusercontent.com/11667761/37342507-5daa08be-268a-11e8-9293-866030b7f201.png)

**Comment by Tybion** [comment]
I have updated the line in Podfile to ..

` pod 'wkb-ios', '~> 1.0.9'`

Note that the instructions in the MD file and Cocoapods need to be updated - they both say 1.0

The Build Settings are consistent with yours.

Even after upgrading to 1.0.9, (and uninstalling and reinstalling wkb-ios) I still get the following ..

```
//  wkb-ios-Bridging-Header.h
//  wkb-ios
//
//  Created by Brian Osborn on 11/23/15.
//  Copyright © 2015 NGA. All rights reserved.

#ifndef wkb_ios_Bridging_Header_h
#define wkb_ios_Bridging_Header_h

#import "wkb_ios.h"
#import "WKBCircularString.h"           'WKBCircularString.h' file not found
```

I can understand why this error appears.  I can't understand why it doesn't appear for you.

**Comment by bosborn** [comment]
Sorry, 1.0 is fine as well to use the newest version 1.x.  Sometimes you may want to specify a full version to protect yourself from unwanted changes.  [From CocoaPods](https://guides.cocoapods.org/using/the-podfile.html):

```
'~> 0.1.2' Version 0.1.2 and the versions up to 0.2, not including 0.2 and higher
'~> 0.1' Version 0.1 and the versions up to 1.0, not including 1.0 and higher
'~> 0' Version 0 and higher, this is basically the same as not having it.
```

**Comment by bosborn** [comment]
I'm not quite sure why you are having that issue.  And you are building using "pod install" and opening the .xcworkspace project?  It sounds like the wkb-ios pod isn't installed correctly.  Did you check the project's Build Phases to make sure WKB was being copied?

![screen shot 2018-03-13 at 4 16 14 pm](https://user-images.githubusercontent.com/11667761/37372869-f5f2b1b2-26d9-11e8-94a0-e6977565d435.png)

And did you verify the Pod is installed in the navigator view?

![screen shot 2018-03-13 at 4 25 09 pm](https://user-images.githubusercontent.com/11667761/37373216-5df84686-26db-11e8-821b-51b3f9078b08.png)

Here is a zip of the project I created:
[swift_test.zip](https://github.com/ngageoint/geopackage-wkb-ios/files/1808836/swift_test.zip)

Built using "pod install" with CocoaPods 1.4.0.

If you want to provide an example project with the failure I can take a look.

**Comment by Tybion** [comment]
Yes, it is installed fine.  I have many Pods as part of my project, and they are all working fine.  wkb-ios is the only Objective-C pod, though.

I also checked Build Phases, and the script is there ..
`"${SRCROOT}/Pods/Target Support Files/Pods-ausgeologymaps/Pods-ausgeologymaps-resources.sh"`

The files are located as follows ..

```
Davids-Air:Pods david$ pwd
/Users/david/XcodeProjects/ausgeologymaps/Pods
Davids-Air:Pods david$ find . -name "*" | grep "wkb-ios"
./Pods.xcodeproj/xcuserdata/david.xcuserdatad/xcschemes/wkb-ios.xcscheme
./Pods.xcodeproj/xcuserdata/david.xcuserdatad/xcschemes/wkb-ios-WKB.xcscheme
./Target Support Files/wkb-ios
./Target Support Files/wkb-ios/wkb-ios.modulemap
./Target Support Files/wkb-ios/wkb-ios-prefix.pch
./Target Support Files/wkb-ios/wkb-ios-umbrella.h
./Target Support Files/wkb-ios/ResourceBundle-WKB-Info.plist
./Target Support Files/wkb-ios/wkb-ios.xcconfig
./Target Support Files/wkb-ios/wkb-ios-dummy.m
./Target Support Files/wkb-ios/Info.plist
./wkb-ios
./wkb-ios/LICENSE
./wkb-ios/README.md
./wkb-ios/wkb-ios
./wkb-ios/wkb-ios/util
./wkb-ios/wkb-ios/util/WKBGeometryEnvelopeBuilder.h
./wkb-ios/wkb-ios/util/WKBGeometryPrinter.h
./wkb-ios/wkb-ios/util/centroid
./wkb-ios/wkb-ios/util/centroid/WKBCentroidPoint.m
./wkb-ios/wkb-ios/util/centroid/WKBCentroidSurface.m
./wkb-ios/wkb-ios/util/centroid/WKBCentroidCurve.h
./wkb-ios/wkb-ios/util/centroid/WKBCentroidSurface.h
./wkb-ios/wkb-ios/util/centroid/WKBCentroidPoint.h
./wkb-ios/wkb-ios/util/centroid/WKBCentroidCurve.m
./wkb-ios/wkb-ios/util/WKBGeometryJSONCompatible.m
./wkb-ios/wkb-ios/util/WKBGeometryUtils.h
./wkb-ios/wkb-ios/util/WKBGeometryEnvelopeBuilder.m
./wkb-ios/wkb-ios/util/sweep
./wkb-ios/wkb-ios/util/sweep/WKBShamosHoey.h
./wkb-ios/wkb-ios/util/sweep/WKBEventTypes.h
./wkb-ios/wkb-ios/util/sweep/WKBEventQueue.m
./wkb-ios/wkb-ios/util/sweep/WKBSegment.m
./wkb-ios/wkb-ios/util/sweep/WKBSweepLine.h
./wkb-ios/wkb-ios/util/sweep/WKBEvent.m
./wkb-ios/wkb-ios/util/sweep/WKBEventTypes.m
./wkb-ios/wkb-ios/util/sweep/WKBShamosHoey.m
./wkb-ios/wkb-ios/util/sweep/WKBSweepLine.m
./wkb-ios/wkb-ios/util/sweep/WKBSegment.h
./wkb-ios/wkb-ios/util/sweep/WKBEventQueue.h
./wkb-ios/wkb-ios/util/sweep/WKBEvent.h
./wkb-ios/wkb-ios/util/WKBGeometryPrinter.m
./wkb-ios/wkb-ios/util/WKBGeometryUtils.m
./wkb-ios/wkb-ios/util/WKBGeometryJSONCompatible.h
./wkb-ios/wkb-ios/io
./wkb-ios/wkb-ios/io/WKBByteReader.h
./wkb-ios/wkb-ios/io/WKBGeometryReader.m
./wkb-ios/wkb-ios/io/WKBGeometryWriter.h
./wkb-ios/wkb-ios/io/WKBByteWriter.m
./wkb-ios/wkb-ios/io/WKBGeometryReader.h
./wkb-ios/wkb-ios/io/WKBByteReader.m
./wkb-ios/wkb-ios/io/WKBByteWriter.h
./wkb-ios/wkb-ios/io/WKBGeometryWriter.m
./wkb-ios/wkb-ios/geom
./wkb-ios/wkb-ios/geom/WKBGeometry.m
./wkb-ios/wkb-ios/geom/WKBMultiPoint.h
./wkb-ios/wkb-ios/geom/WKBMultiLineString.h
./wkb-ios/wkb-ios/geom/WKBLineString.h
./wkb-ios/wkb-ios/geom/WKBCurvePolygon.h
./wkb-ios/wkb-ios/geom/WKBCompoundCurve.h
./wkb-ios/wkb-ios/geom/WKBTriangle.m
./wkb-ios/wkb-ios/geom/WKBMultiCurve.m
./wkb-ios/wkb-ios/geom/WKBMultiSurface.h
./wkb-ios/wkb-ios/geom/WKBGeometryTypes.h
./wkb-ios/wkb-ios/geom/WKBCurve.h
./wkb-ios/wkb-ios/geom/WKBCircularString.h
./wkb-ios/wkb-ios/geom/WKBPolyhedralSurface.m
./wkb-ios/wkb-ios/geom/WKBSurface.m
./wkb-ios/wkb-ios/geom/WKBGeometryCollection.m
./wkb-ios/wkb-ios/geom/WKBMultiPolygon.h
./wkb-ios/wkb-ios/geom/WKBTIN.h
./wkb-ios/wkb-ios/geom/WKBPolygon.m
./wkb-ios/wkb-ios/geom/WKBGeometryEnvelope.m
./wkb-ios/wkb-ios/geom/WKBPoint.m
./wkb-ios/wkb-ios/geom/WKBLineString.m
./wkb-ios/wkb-ios/geom/WKBMultiLineString.m
./wkb-ios/wkb-ios/geom/WKBMultiPoint.m
./wkb-ios/wkb-ios/geom/WKBGeometry.h
./wkb-ios/wkb-ios/geom/WKBMultiCurve.h
./wkb-ios/wkb-ios/geom/WKBTriangle.h
./wkb-ios/wkb-ios/geom/WKBCompoundCurve.m
./wkb-ios/wkb-ios/geom/WKBCurvePolygon.m
./wkb-ios/wkb-ios/geom/WKBGeometryCollection.h
./wkb-ios/wkb-ios/geom/WKBSurface.h
./wkb-ios/wkb-ios/geom/WKBPolyhedralSurface.h
./wkb-ios/wkb-ios/geom/WKBCurve.m
./wkb-ios/wkb-ios/geom/WKBCircularString.m
./wkb-ios/wkb-ios/geom/WKBGeometryTypes.m
./wkb-ios/wkb-ios/geom/WKBMultiSurface.m
./wkb-ios/wkb-ios/geom/WKBPoint.h
./wkb-ios/wkb-ios/geom/WKBGeometryEnvelope.h
./wkb-ios/wkb-ios/geom/WKBPolygon.h
./wkb-ios/wkb-ios/geom/WKBTIN.m
./wkb-ios/wkb-ios/geom/WKBMultiPolygon.m
./wkb-ios/wkb-ios/wkb_ios.h
./wkb-ios/wkb-ios/wkb-ios-Bridging-Header.h
./wkb-ios/wkb-ios/Info.plist
```
Since the answer is not coming easily, I am happy to leave this as unsolved, since I have a work-around.  Maybe someone reading this will come up with the answer.

In the end, it comes down to my installation not looking in sub-folders for .h files, whereas your installation does.

**Comment by bosborn** [comment]
Closing this non simple features version of the library issue.  Feel free to reopen if someone experiences a similar issue and we can investigate.  The following note provides some Swift & CocoaPods project setup guidance.
https://github.com/ngageoint/geopackage-ios/tree/master/docs/examples/swift/GeoPackage-to-go-iOS#a-note-about-swift-and-cocoapods
